# Generated by Django 4.2.2 on 2023-07-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='actyoe',
            new_name='actype',
        ),
    ]
